"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Edit, RefreshCw, Trash2, ChevronDown, ChevronUp, BarChart, LineChart, PieChart, Activity } from "lucide-react"
import type { Slide, Role } from "@/app/generate/page"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Loader } from "@/components/loader"
import { ChartComponent } from "@/components/chart-component"
import { getRoleColor } from "@/lib/utils"

interface SlideCardProps {
  slide: Slide
  onEdit: (updatedSlide: Partial<Slide>) => void
  onDelete: () => void
  onRegenerate: () => void
  role: Role
}

export function SlideCard({ slide, onEdit, onDelete, onRegenerate, role }: SlideCardProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [isExpanded, setIsExpanded] = useState(true)
  const [isRegenerating, setIsRegenerating] = useState(false)
  const [editedTitle, setEditedTitle] = useState(slide.title)
  const [editedContent, setEditedContent] = useState(slide.content)
  const [editedBullets, setEditedBullets] = useState(slide.bullets.join("\n"))
  const [editedNotes, setEditedNotes] = useState(slide.notes || "")

  const roleColor = getRoleColor(role)

  // Generate random chart data if not provided
  const chartData = slide.chartData || generateRandomChartData(slide.chartType || getRandomChartType())
  const chartType = slide.chartType || getRandomChartType()

  function getRandomChartType() {
    const types = ["bar", "line", "pie", "area"]
    return types[Math.floor(Math.random() * types.length)] as "bar" | "line" | "pie" | "area"
  }

  function generateRandomChartData(type: "bar" | "line" | "pie" | "area") {
    if (type === "pie") {
      return [
        { name: "Segment A", value: Math.floor(Math.random() * 100) + 20 },
        { name: "Segment B", value: Math.floor(Math.random() * 100) + 20 },
        { name: "Segment C", value: Math.floor(Math.random() * 100) + 20 },
        { name: "Segment D", value: Math.floor(Math.random() * 100) + 20 },
      ]
    }

    return [
      { name: "Jan", value: Math.floor(Math.random() * 100) + 20 },
      { name: "Feb", value: Math.floor(Math.random() * 100) + 20 },
      { name: "Mar", value: Math.floor(Math.random() * 100) + 20 },
      { name: "Apr", value: Math.floor(Math.random() * 100) + 20 },
      { name: "May", value: Math.floor(Math.random() * 100) + 20 },
      { name: "Jun", value: Math.floor(Math.random() * 100) + 20 },
    ]
  }

  const handleSave = () => {
    onEdit({
      title: editedTitle,
      content: editedContent,
      bullets: editedBullets.split("\n").filter((bullet) => bullet.trim() !== ""),
      notes: editedNotes,
    })
    setIsEditing(false)
  }

  const handleCancel = () => {
    setEditedTitle(slide.title)
    setEditedContent(slide.content)
    setEditedBullets(slide.bullets.join("\n"))
    setEditedNotes(slide.notes || "")
    setIsEditing(false)
  }

  const handleRegenerate = async () => {
    setIsRegenerating(true)
    await onRegenerate()
    setIsRegenerating(false)
  }

  const getChartIcon = () => {
    switch (chartType) {
      case "bar":
        return <BarChart className="h-4 w-4" />
      case "line":
        return <LineChart className="h-4 w-4" />
      case "pie":
        return <PieChart className="h-4 w-4" />
      case "area":
        return <Activity className="h-4 w-4" />
      default:
        return <BarChart className="h-4 w-4" />
    }
  }

  return (
    <motion.div whileHover={{ y: -5 }} transition={{ duration: 0.2 }}>
      <Card
        className={`backdrop-blur-sm bg-white/80 dark:bg-gray-900/80 border border-gray-200/50 dark:border-gray-800/50 shadow-lg overflow-hidden`}
      >
        <CardHeader className={`pb-2 border-l-4`} style={{ borderColor: roleColor }}>
          <div className="flex items-center justify-between">
            <CardTitle className="text-xl">{slide.title}</CardTitle>
            <Button variant="ghost" size="icon" onClick={() => setIsExpanded(!isExpanded)}>
              {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
            </Button>
          </div>
          <div className="text-xs text-gray-500 flex items-center mt-1">
            <div className="flex items-center">
              <div className="w-2 h-2 rounded-full mr-1" style={{ backgroundColor: roleColor }}></div>
              Generated by {role}
            </div>
          </div>
        </CardHeader>

        {isExpanded && (
          <>
            <CardContent className="pt-4">
              {isEditing ? (
                <div className="space-y-4">
                  <div>
                    <Input
                      value={editedTitle}
                      onChange={(e) => setEditedTitle(e.target.value)}
                      placeholder="Slide title"
                      className="mb-2 bg-white/50 dark:bg-gray-800/50"
                    />
                    <Textarea
                      value={editedContent}
                      onChange={(e) => setEditedContent(e.target.value)}
                      placeholder="Slide content"
                      className="mb-2 bg-white/50 dark:bg-gray-800/50"
                    />
                    <Textarea
                      value={editedBullets}
                      onChange={(e) => setEditedBullets(e.target.value)}
                      placeholder="Bullet points (one per line)"
                      className="mb-2 bg-white/50 dark:bg-gray-800/50"
                    />
                    <Textarea
                      value={editedNotes}
                      onChange={(e) => setEditedNotes(e.target.value)}
                      placeholder="Speaker notes (optional)"
                      className="bg-white/50 dark:bg-gray-800/50"
                    />
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <p>{slide.content}</p>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {slide.bullets.length > 0 && (
                      <div>
                        <h4 className="text-sm font-medium mb-2">Key Points:</h4>
                        <ul className="list-disc pl-5 space-y-1">
                          {slide.bullets.map((bullet, index) => (
                            <motion.li
                              key={index}
                              initial={{ opacity: 0, x: -10 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ duration: 0.3, delay: index * 0.1 }}
                            >
                              {bullet}
                            </motion.li>
                          ))}
                        </ul>
                      </div>
                    )}

                    <motion.div
                      className="h-[200px] w-full"
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{ duration: 0.5, delay: 0.2 }}
                    >
                      <div className="flex items-center mb-2">
                        {getChartIcon()}
                        <span className="text-sm font-medium ml-1">Data Visualization</span>
                      </div>
                      <ChartComponent type={chartType} data={chartData} color={roleColor} />
                    </motion.div>
                  </div>

                  {slide.notes && (
                    <motion.div
                      className="mt-4 border-t pt-2"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.5, delay: 0.3 }}
                    >
                      <p className="text-sm font-medium">Speaker Notes:</p>
                      <p className="text-sm text-gray-600 dark:text-gray-400">{slide.notes}</p>
                    </motion.div>
                  )}
                </div>
              )}
            </CardContent>
            <CardFooter className="flex justify-between">
              {isEditing ? (
                <div className="flex space-x-2">
                  <Button variant="outline" onClick={handleCancel}>
                    Cancel
                  </Button>
                  <Button onClick={handleSave} style={{ backgroundColor: roleColor }}>
                    Save Changes
                  </Button>
                </div>
              ) : (
                <div className="flex space-x-2">
                  <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                    <Edit className="mr-2 h-4 w-4" /> Edit
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleRegenerate} disabled={isRegenerating}>
                    {isRegenerating ? <Loader className="mr-2 h-4 w-4" /> : <RefreshCw className="mr-2 h-4 w-4" />}
                    Regenerate
                  </Button>
                  <Button variant="outline" size="sm" onClick={onDelete}>
                    <Trash2 className="mr-2 h-4 w-4" /> Delete
                  </Button>
                </div>
              )}
            </CardFooter>
          </>
        )}
      </Card>
    </motion.div>
  )
}
